### ISSUE TITLE
WooCommerce purchased products as tags

### ISSUE THREAD

**Issue by scottbuscemi** [scottbuscemi/ActiveCampaign-WordPress-Opt-Ins#2]
When a customer completes a WooCommerce order, each product they purchased should be added as a tag to their contact within ActiveCampaign.

## Back-end Enhancement

We need to add a checkbox to the plugin settings page that states "Add products to ActiveCampaign as contact tags".
* This should be on by default
* This should save as an option in the wp_options table

## WooCommerce integration additions

We should add the tags after the purchase is complete and payment is received/confirmed.
* Test to make sure the tags are added even for contacts that were already in ActiveCampaign before
* Test to make sure the tags are added for new contacts that were not in ActiveCampaign previously
* Test to make sure this works for tags that already existed and for creating new tags

**Comment by mrphpguru** [comment]
Enhancement done as req. Please chk and provide your valuable feedback.

**Comment by scottbuscemi** [comment]
Whenever I checkmark the 'save products' then save the page, the checkbox goes un-checked. Is it staying for you? https://www.useloom.com/share/23e89ff344894b5b8b6e2cf0768d8f6a

**Comment by scottbuscemi** [comment]
I fixed the saving of the checkbox in 7623e5cc4f69c9c338dba6bd4ea69897db4b7961

**Comment by scottbuscemi** [comment]
The main file was still referencing /includes in the file... did you QA this successfully?
