### ISSUE TITLE
Keep API credential options when plugin is deleted/reinstalled

### ISSUE THREAD

**Issue by scottbuscemi** [scottbuscemi/ActiveCampaign-WordPress-Opt-Ins#3]
Currently, deleting the plugin then re-installing it requires the user to re-enter in their ActiveCampaign details on the "AC Registration" options page.

We should keep these details in the options table when the plugin is deleted to make it easy to manually upgrade the plugin to a new version.

**Comment by mrphpguru** [comment]
Issue solved and committed in my branch
